<orderList>
	<orderListInfo>
		<olId>220001353771</olId>
		<olNbr>220001353771</olNbr>
		<olTypeCd>3</olTypeCd>
		<staffId>130000001002</staffId>
		<channelId>310068141</channelId>
		<channelSpecId>2</channelSpecId>
		<areaId>22016</areaId>
		<areaName>天津市_宝坻</areaName>
		<channelName>宝坻-爱伟通讯-大白庄镇营业厅-合作厅</channelName>
		<staffName>郝建军</staffName>
		<createDt>20110613100241</createDt>
	</orderListInfo>
	<custOrderList>
		<partyId>223000451701</partyId>
		<partyName>天津市蓟县人民医院</partyName>
		<areaName>天津市</areaName>
		<partyType>组织</partyType>
		<addressStr>天津市蓟县人民医院</addressStr>
		<identityType>身份证</identityType>
		<identityCardNo>1111</identityCardNo>
		<linkName>天津市蓟县人民医院</linkName>
		<linkNumber>82852731</linkNumber>
		<partyChangeInfo/>
		<orderEvent>
			<prodInfos>
				<prodInfo>
					<prodId>223206922417</prodId>
					<prodSpecId>379</prodSpecId>
					<prodSpecName>CDMA</prodSpecName>
					<accessNumber>15342048663</accessNumber>
					<prodAction>新装</prodAction>
					<feeTypeInfo>
						<feeType>
							<feeTypeId>2</feeTypeId>
							<feeTypeName>仅预付</feeTypeName>
							<action>新</action>
							<feeTypeState>ADD</feeTypeState>
						</feeType>
					</feeTypeInfo>
					<boProdSpec>
						<prodSpecId>379</prodSpecId>
						<prodSpecName>CDMA</prodSpecName>
						<action>新</action>
					</boProdSpec>
					<servInfo>
						<servId>221288327061</servId>
						<servSpecId>9</servSpecId>
						<action>开</action>
						<servSpecName>国内长途权限</servSpecName>
					</servInfo>
					<servInfo>
						<servId>221288328061</servId>
						<servSpecId>1022</servSpecId>
						<action>开</action>
						<servSpecName>天翼_互联网数据业务</servSpecName>
					</servInfo>
					<servInfo>
						<servId>221288329061</servId>
						<servSpecId>1006</servSpecId>
						<action>开</action>
						<servSpecName>天翼_国内漫游</servSpecName>
					</servInfo>
					<servInfo>
						<servId>221288330061</servId>
						<servSpecId>1015</servSpecId>
						<action>开</action>
						<servSpecName>天翼_隐含前转</servSpecName>
					</servInfo>
					<servInfo>
						<servId>221288331061</servId>
						<servSpecId>1001</servSpecId>
						<action>开</action>
						<servSpecName>天翼_短消息</servSpecName>
					</servInfo>
					<servInfo>
						<servId>221288332061</servId>
						<servSpecId>1000</servSpecId>
						<action>开</action>
						<servSpecName>天翼_不可及转移</servSpecName>
					</servInfo>
					<servInfo>
						<servId>221288333061</servId>
						<servSpecId>31</servSpecId>
						<action>开</action>
						<servSpecName>遇忙转移</servSpecName>
					</servInfo>
					<servInfo>
						<servId>221288334061</servId>
						<servSpecId>28</servSpecId>
						<action>开</action>
						<servSpecName>无应答转移</servSpecName>
					</servInfo>
					<servInfo>
						<servId>221288335061</servId>
						<servSpecId>13</servSpecId>
						<action>开</action>
						<servSpecName>无条件呼叫转移</servSpecName>
					</servInfo>
					<servInfo>
						<servId>221288336061</servId>
						<servSpecId>12</servSpecId>
						<action>开</action>
						<servSpecName>呼叫等待</servSpecName>
					</servInfo>
					<servInfo>
						<servId>221288337061</servId>
						<servSpecId>11</servSpecId>
						<action>开</action>
						<servSpecName>呼叫保持</servSpecName>
					</servInfo>
					<servInfo>
						<servId>221288338061</servId>
						<servSpecId>1025</servSpecId>
						<action>开</action>
						<servSpecName>天翼_EVDO</servSpecName>
					</servInfo>
					<servInfo>
						<servId>221288339061</servId>
						<servSpecId>20</servSpecId>
						<action>开</action>
						<servSpecName>来电显示</servSpecName>
					</servInfo>
					<servInfo>
						<servId>221288340061</servId>
						<servSpecId>111</servSpecId>
						<action>开</action>
						<servSpecName>天翼视讯全能看5元</servSpecName>
					</servInfo>
					<servInfo>
						<servId>221288341061</servId>
						<servSpecId>167</servSpecId>
						<action>开</action>
						<servSpecName>189邮箱2G_包月0元</servSpecName>
					</servInfo>
					<servInfo>
						<servId>221288342061</servId>
						<servSpecId>1010</servSpecId>
						<action>开</action>
						<servSpecName>天翼_七彩铃音</servSpecName>
					</servInfo>
					<servInfo>
						<servId>221288343061</servId>
						<servSpecId>1011</servSpecId>
						<action>开</action>
						<servSpecName>天翼_8元漏电提醒</servSpecName>
					</servInfo>
				</prodInfo>
			</prodInfos>
			<offerInfos>
				<offerInfo>
					<offerId>225000735121</offerId>
					<offerSpecId>500000051</offerSpecId>
					<offerSpecName>市民礼包199/24月</offerSpecName>
					<offerSpecDesc>市民礼包199/24月</offerSpecDesc>
					<action>新</action>
					<type>4</type>
					<startDt>13-6月 -11</startDt>
					<timeUnit>帐期</timeUnit>
					<effTime>25</effTime>
				</offerInfo>
				<offerInfo>
					<offerId>225000735122</offerId>
					<offerSpecId>511001386</offerSpecId>
					<offerSpecName>乐享3G全能版129</offerSpecName>
					<offerSpecDesc>乐享3G全能版129</offerSpecDesc>
					<action>新</action>
					<type>4</type>
					<startDt>13-6月 -11</startDt>
					<timeUnit>帐期</timeUnit>
				</offerInfo>
				<offerInfo>
					<offerId>225000735123</offerId>
					<offerSpecId>51000</offerSpecId>
					<offerSpecName>天翼基本资费</offerSpecName>
					<offerSpecDesc>天翼基本资费</offerSpecDesc>
					<action>新</action>
					<type>4</type>
					<startDt>竣工后</startDt>
					<timeUnit>帐期</timeUnit>
				</offerInfo>
				<offerInfo>
					<offerId>225000735124</offerId>
					<offerSpecId>2209</offerSpecId>
					<offerSpecName>国内长途权限</offerSpecName>
					<offerSpecDesc>国内长途权限</offerSpecDesc>
					<action>新</action>
					<type>4</type>
					<startDt>竣工后</startDt>
					<timeUnit>月</timeUnit>
				</offerInfo>
				<offerInfo>
					<offerId>225000735125</offerId>
					<offerSpecId>2201022</offerSpecId>
					<offerSpecName>天翼_互联网数据业务</offerSpecName>
					<offerSpecDesc>天翼_互联网数据业务</offerSpecDesc>
					<action>新</action>
					<type>4</type>
					<startDt>竣工后</startDt>
					<timeUnit>月</timeUnit>
				</offerInfo>
				<offerInfo>
					<offerId>225000735126</offerId>
					<offerSpecId>2201006</offerSpecId>
					<offerSpecName>天翼_国内漫游</offerSpecName>
					<offerSpecDesc>天翼_国内漫游</offerSpecDesc>
					<action>新</action>
					<type>4</type>
					<startDt>竣工后</startDt>
					<timeUnit>月</timeUnit>
				</offerInfo>
				<offerInfo>
					<offerId>225000735127</offerId>
					<offerSpecId>2201015</offerSpecId>
					<offerSpecName>天翼_隐含前转</offerSpecName>
					<offerSpecDesc>天翼_隐含前转</offerSpecDesc>
					<action>新</action>
					<type>4</type>
					<startDt>竣工后</startDt>
					<timeUnit>月</timeUnit>
				</offerInfo>
				<offerInfo>
					<offerId>225000735128</offerId>
					<offerSpecId>2201001</offerSpecId>
					<offerSpecName>天翼_短消息</offerSpecName>
					<offerSpecDesc>天翼_短消息</offerSpecDesc>
					<action>新</action>
					<type>4</type>
					<startDt>竣工后</startDt>
					<timeUnit>月</timeUnit>
				</offerInfo>
				<offerInfo>
					<offerId>225000735129</offerId>
					<offerSpecId>2201000</offerSpecId>
					<offerSpecName>天翼_不可及转移</offerSpecName>
					<offerSpecDesc>天翼_不可及转移</offerSpecDesc>
					<action>新</action>
					<type>4</type>
					<startDt>竣工后</startDt>
					<timeUnit>月</timeUnit>
				</offerInfo>
				<offerInfo>
					<offerId>225000735130</offerId>
					<offerSpecId>22031</offerSpecId>
					<offerSpecName>遇忙转移</offerSpecName>
					<offerSpecDesc>遇忙转移</offerSpecDesc>
					<action>新</action>
					<type>4</type>
					<startDt>竣工后</startDt>
					<timeUnit>月</timeUnit>
				</offerInfo>
				<offerInfo>
					<offerId>225000735131</offerId>
					<offerSpecId>22028</offerSpecId>
					<offerSpecName>无应答转移</offerSpecName>
					<offerSpecDesc>无应答转移</offerSpecDesc>
					<action>新</action>
					<type>4</type>
					<startDt>竣工后</startDt>
					<timeUnit>月</timeUnit>
				</offerInfo>
				<offerInfo>
					<offerId>225000735132</offerId>
					<offerSpecId>22013</offerSpecId>
					<offerSpecName>无条件呼叫转移</offerSpecName>
					<offerSpecDesc>无条件呼叫转移</offerSpecDesc>
					<action>新</action>
					<type>4</type>
					<startDt>竣工后</startDt>
					<timeUnit>月</timeUnit>
				</offerInfo>
				<offerInfo>
					<offerId>225000735133</offerId>
					<offerSpecId>22012</offerSpecId>
					<offerSpecName>呼叫等待</offerSpecName>
					<offerSpecDesc>呼叫等待</offerSpecDesc>
					<action>新</action>
					<type>4</type>
					<startDt>竣工后</startDt>
					<timeUnit>月</timeUnit>
				</offerInfo>
				<offerInfo>
					<offerId>225000735134</offerId>
					<offerSpecId>22011</offerSpecId>
					<offerSpecName>呼叫保持</offerSpecName>
					<offerSpecDesc>呼叫保持</offerSpecDesc>
					<action>新</action>
					<type>4</type>
					<startDt>竣工后</startDt>
					<timeUnit>月</timeUnit>
				</offerInfo>
				<offerInfo>
					<offerId>225000735135</offerId>
					<offerSpecId>2201025</offerSpecId>
					<offerSpecName>天翼_EVDO</offerSpecName>
					<offerSpecDesc>天翼_EVDO</offerSpecDesc>
					<action>新</action>
					<type>4</type>
					<startDt>竣工后</startDt>
					<timeUnit>月</timeUnit>
				</offerInfo>
				<offerInfo>
					<offerId>225000735122</offerId>
					<offerSpecId>511001386</offerSpecId>
					<offerSpecName>乐享3G全能版129</offerSpecName>
					<offerSpecDesc>乐享3G全能版129</offerSpecDesc>
					<action>原</action>
					<type>4</type>
					<startDt>13-6月 -11</startDt>
					<timeUnit>帐期</timeUnit>
				</offerInfo>
				<offerInfo>
					<offerId>225000735122</offerId>
					<offerSpecId>511001386</offerSpecId>
					<offerSpecName>乐享3G全能版129</offerSpecName>
					<offerSpecDesc>乐享3G全能版129</offerSpecDesc>
					<action>原</action>
					<type>4</type>
					<startDt>13-6月 -11</startDt>
					<timeUnit>帐期</timeUnit>
				</offerInfo>
				<offerInfo>
					<offerId>225000735122</offerId>
					<offerSpecId>511001386</offerSpecId>
					<offerSpecName>乐享3G全能版129</offerSpecName>
					<offerSpecDesc>乐享3G全能版129</offerSpecDesc>
					<action>原</action>
					<type>4</type>
					<startDt>13-6月 -11</startDt>
					<timeUnit>帐期</timeUnit>
				</offerInfo>
				<offerInfo>
					<offerId>225000735122</offerId>
					<offerSpecId>511001386</offerSpecId>
					<offerSpecName>乐享3G全能版129</offerSpecName>
					<offerSpecDesc>乐享3G全能版129</offerSpecDesc>
					<action>原</action>
					<type>4</type>
					<startDt>13-6月 -11</startDt>
					<timeUnit>帐期</timeUnit>
				</offerInfo>
				<offerInfo>
					<offerId>225000735122</offerId>
					<offerSpecId>511001386</offerSpecId>
					<offerSpecName>乐享3G全能版129</offerSpecName>
					<offerSpecDesc>乐享3G全能版129</offerSpecDesc>
					<action>原</action>
					<type>4</type>
					<startDt>13-6月 -11</startDt>
					<timeUnit>帐期</timeUnit>
				</offerInfo>
			</offerInfos>
			<busiOrderInfos>
				<busiOrderInfo>
					<boActionTypeCd>S1</boActionTypeCd>
					<boActionName>订购</boActionName>
					<actionClassCd>3</actionClassCd>
					<objName>乐享3G全能版129</objName>
				</busiOrderInfo>
				<busiOrderInfo>
					<boActionTypeCd>S1</boActionTypeCd>
					<boActionName>订购</boActionName>
					<actionClassCd>3</actionClassCd>
					<objName>市民礼包199/24月</objName>
				</busiOrderInfo>
				<busiOrderInfo>
					<boActionTypeCd>S1</boActionTypeCd>
					<boActionName>订购</boActionName>
					<actionClassCd>3</actionClassCd>
					<objName>天翼基本资费</objName>
				</busiOrderInfo>
				<busiOrderInfo>
					<boActionTypeCd>S1</boActionTypeCd>
					<boActionName>订购附属销售品</boActionName>
					<actionClassCd>3</actionClassCd>
					<objName>国内长途权限</objName>
				</busiOrderInfo>
				<busiOrderInfo>
					<boActionTypeCd>S1</boActionTypeCd>
					<boActionName>订购附属销售品</boActionName>
					<actionClassCd>3</actionClassCd>
					<objName>呼叫保持</objName>
				</busiOrderInfo>
				<busiOrderInfo>
					<boActionTypeCd>S1</boActionTypeCd>
					<boActionName>订购附属销售品</boActionName>
					<actionClassCd>3</actionClassCd>
					<objName>呼叫等待</objName>
				</busiOrderInfo>
				<busiOrderInfo>
					<boActionTypeCd>S1</boActionTypeCd>
					<boActionName>订购附属销售品</boActionName>
					<actionClassCd>3</actionClassCd>
					<objName>天翼_EVDO</objName>
				</busiOrderInfo>
				<busiOrderInfo>
					<boActionTypeCd>S1</boActionTypeCd>
					<boActionName>订购附属销售品</boActionName>
					<actionClassCd>3</actionClassCd>
					<objName>天翼_不可及转移</objName>
				</busiOrderInfo>
				<busiOrderInfo>
					<boActionTypeCd>S1</boActionTypeCd>
					<boActionName>订购附属销售品</boActionName>
					<actionClassCd>3</actionClassCd>
					<objName>天翼_短消息</objName>
				</busiOrderInfo>
				<busiOrderInfo>
					<boActionTypeCd>S1</boActionTypeCd>
					<boActionName>订购附属销售品</boActionName>
					<actionClassCd>3</actionClassCd>
					<objName>天翼_国内漫游</objName>
				</busiOrderInfo>
				<busiOrderInfo>
					<boActionTypeCd>S1</boActionTypeCd>
					<boActionName>订购附属销售品</boActionName>
					<actionClassCd>3</actionClassCd>
					<objName>天翼_互联网数据业务</objName>
				</busiOrderInfo>
				<busiOrderInfo>
					<boActionTypeCd>S1</boActionTypeCd>
					<boActionName>订购附属销售品</boActionName>
					<actionClassCd>3</actionClassCd>
					<objName>天翼_隐含前转</objName>
				</busiOrderInfo>
				<busiOrderInfo>
					<boActionTypeCd>S1</boActionTypeCd>
					<boActionName>订购附属销售品</boActionName>
					<actionClassCd>3</actionClassCd>
					<objName>无条件呼叫转移</objName>
				</busiOrderInfo>
				<busiOrderInfo>
					<boActionTypeCd>S1</boActionTypeCd>
					<boActionName>订购附属销售品</boActionName>
					<actionClassCd>3</actionClassCd>
					<objName>无应答转移</objName>
				</busiOrderInfo>
				<busiOrderInfo>
					<boActionTypeCd>S1</boActionTypeCd>
					<boActionName>订购附属销售品</boActionName>
					<actionClassCd>3</actionClassCd>
					<objName>遇忙转移</objName>
				</busiOrderInfo>
			</busiOrderInfos>
			<boAccountRelas>
				<boAccountRela>
					<chargeItemCd>0</chargeItemCd>
					<acctCd>22000000006003329</acctCd>
					<acctPartyId>223000451701</acctPartyId>
					<acctPartyName>天津市蓟县人民医院</acctPartyName>
					<action>新</action>
					<paymentAcct>
						<paymentAcctId>220012804947</paymentAcctId>
						<payAcctType>现金</payAcctType>
						<payAction>新</payAction>
					</paymentAcct>
				</boAccountRela>
			</boAccountRelas>
			<state>1</state>
		</orderEvent>
		<orderEvent>
			<busiOrderInfos>
				<busiOrderInfo>
					<boActionTypeCd>A1</boActionTypeCd>
					<boActionName>创建帐户</boActionName>
					<actionClassCd>2</actionClassCd>
					<staffCd>130000001002</staffCd>
					<staffName>郝建军</staffName>
				</busiOrderInfo>
			</busiOrderInfos>
			<boAccountInfos>
				<boAccountInfo>
					<acctCd>22000000006003329</acctCd>
					<partyId>223000451701</partyId>
					<acctName>天津市蓟县人民医院</acctName>
					<busiPwd></busiPwd>
					<limitQty>
					</limitQty>
					<prodId>
					</prodId>
					<action>ADD</action>
				</boAccountInfo>
			</boAccountInfos>
		</orderEvent>
	</custOrderList>
	<pointExchange>
		<info>
		</info>
	</pointExchange>
</orderList>
