git update-index --assume-unchanged ./ecs-common/.settings/org.eclipse.core.resources.prefs
git update-index --assume-unchanged ./ecs-common/.settings/org.eclipse.jdt.core.prefs
git update-index --assume-unchanged ./ecs-common/.settings/org.eclipse.m2e.core.prefs
git update-index --assume-unchanged ./ecs-common/.settings/org.eclipse.wst.common.component
git update-index --assume-unchanged ./ecs-common/.settings/org.eclipse.wst.common.project.facet.core.xml
git update-index --assume-unchanged ./ecs-common/.settings/org.eclipse.wst.validation.prefs
git update-index --assume-unchanged ./ecsp-core/.settings/org.eclipse.core.resources.prefs
git update-index --assume-unchanged ./ecsp-core/.settings/org.eclipse.jdt.core.prefs
git update-index --assume-unchanged ./ecsp-core/.settings/org.eclipse.m2e.core.prefs
git update-index --assume-unchanged ./ecsp-core/.settings/org.eclipse.wst.common.component
git update-index --assume-unchanged ./ecsp-core/.settings/org.eclipse.wst.common.project.facet.core.xml
git update-index --assume-unchanged ./ecsp-parent/.settings/org.eclipse.core.resources.prefs
git update-index --assume-unchanged ./ecsp-parent/.settings/org.eclipse.jdt.core.prefs
git update-index --assume-unchanged ./ecsp-parent/.settings/org.eclipse.m2e.core.prefs
git update-index --assume-unchanged ./ecsp-web/.externalToolBuilders/org.eclipse.wst.jsdt.core.javascriptValidator
git update-index --assume-unchanged ./ecsp-web/.settings/org.eclipse.core.resources.prefs
git update-index --assume-unchanged ./ecsp-web/.settings/org.eclipse.jdt.core.prefs
git update-index --assume-unchanged ./ecsp-web/.settings/org.eclipse.m2e.core.prefs
git update-index --assume-unchanged ./ecsp-web/.settings/org.eclipse.wst.common.component
git update-index --assume-unchanged ./ecsp-web/.settings/org.eclipse.wst.common.project.facet.core.xml
git update-index --assume-unchanged ./ecsp-web/.settings/org.eclipse.wst.jsdt.ui.superType.container
git update-index --assume-unchanged ./ecsp-web/.settings/org.eclipse.wst.jsdt.ui.superType.name
git update-index --assume-unchanged ./ecsp-web/.settings/org.eclipse.wst.validation.prefs
git update-index --assume-unchanged ./lte-portal-4G/.externalToolBuilders/org.eclipse.wst.jsdt.core.javascriptValidator.launch
git update-index --assume-unchanged ./lte-portal-4G/.settings/org.eclipse.core.resources.prefs
git update-index --assume-unchanged ./lte-portal-4G/.settings/org.eclipse.jdt.core.prefs
git update-index --assume-unchanged ./lte-portal-4G/.settings/org.eclipse.m2e.core.prefs
git update-index --assume-unchanged ./lte-portal-4G/.settings/org.eclipse.wst.common.component
git update-index --assume-unchanged ./lte-portal-4G/.settings/org.eclipse.wst.common.project.facet.core.xml
git update-index --assume-unchanged ./lte-portal-4G/.settings/org.eclipse.wst.html.core.prefs
git update-index --assume-unchanged ./lte-portal-4G/.settings/org.eclipse.wst.jsdt.ui.superType.container
git update-index --assume-unchanged ./lte-portal-4G/.settings/org.eclipse.wst.jsdt.ui.superType.name
git update-index --assume-unchanged ./lte-service-client/.settings/org.eclipse.core.resources.prefs
git update-index --assume-unchanged ./lte-service-client/.settings/org.eclipse.jdt.core.prefs
git update-index --assume-unchanged ./lte-service-client/.settings/org.eclipse.m2e.core.prefs
git update-index --assume-unchanged ./lte-service-client/.settings/org.eclipse.wst.common.component
git update-index --assume-unchanged ./lte-service-client/.settings/org.eclipse.wst.common.project.facet.core.xml
git update-index --assume-unchanged ./lte-service-client/.settings/org.eclipse.wst.validation.prefs
git update-index --assume-unchanged ./servicePack-LteCore/.settings/org.eclipse.core.resources.prefs
git update-index --assume-unchanged ./servicePack-LteCore/.settings/org.eclipse.jdt.core.prefs
git update-index --assume-unchanged ./servicePack-LteCore/.settings/org.eclipse.m2e.core.prefs
git update-index --assume-unchanged ./servicePack-LteCore/.settings/org.eclipse.wst.common.component
git update-index --assume-unchanged ./servicePack-LteCore/.settings/org.eclipse.wst.common.project.facet.core.xml
git update-index --assume-unchanged ./servicePack-LteCore/.settings/org.eclipse.wst.validation.prefs
git update-index --assume-unchanged ./ecs-common/.classpath
git update-index --assume-unchanged ./ecsp-core/.classpath
git update-index --assume-unchanged ./ecsp-parent/.classpath
git update-index --assume-unchanged ./ecsp-web/.classpath
git update-index --assume-unchanged ./lte-parent/.classpath
git update-index --assume-unchanged ./lte-portal-4G/.classpath
git update-index --assume-unchanged ./lte-service-client/.classpath
git update-index --assume-unchanged ./servicePack-LteCore/.classpath

git update-index --assume-unchanged ./unifyLogin/.settings/.jsdtscope
git update-index --assume-unchanged ./unifyLogin/.settings/org.eclipse.core.resources.prefs
git update-index --assume-unchanged ./unifyLogin/.settings/org.eclipse.jdt.core.prefs
git update-index --assume-unchanged ./unifyLogin/.settings/org.eclipse.wst.common.component
git update-index --assume-unchanged ./unifyLogin/.settings/org.eclipse.wst.common.project.facet.core.xml
git update-index --assume-unchanged ./unifyLogin/.settings/org.eclipse.wst.jsdt.ui.superType.container
git update-index --assume-unchanged ./unifyLogin/.settings/org.eclipse.wst.jsdt.ui.superType.name

git update-index --assume-unchanged ./app-portal-4G/.settings/.jsdtscope
git update-index --assume-unchanged ./app-portal-4G/.settings/org.eclipse.core.resources.prefs
git update-index --assume-unchanged ./app-portal-4G/.settings/org.eclipse.jdt.core.prefs
git update-index --assume-unchanged ./app-portal-4G/.settings/org.eclipse.m2e.core.prefs
git update-index --assume-unchanged ./app-portal-4G/.settings/org.eclipse.wst.common.component
git update-index --assume-unchanged ./app-portal-4G/.settings/org.eclipse.wst.common.project.facet.core.xml
git update-index --assume-unchanged ./app-portal-4G/.settings/org.eclipse.wst.jsdt.ui.superType.container
git update-index --assume-unchanged ./app-portal-4G/.settings/org.eclipse.wst.jsdt.ui.superType.name
git update-index --assume-unchanged ./app-portal-4G/.settings/org.eclipse.wst.validation.prefs
git update-index --assume-unchanged ./app-portal-4G/.settings/org.eclipse.wst.xsl.core.prefs