<?xml version="1.0" encoding="UTF-8"?>
<ContractRoot>
	<TcpCont>
		<TransactionID>${TcpCont.TransactionID}</TransactionID>
		<ActionCode>${TcpCont.ActionCode}</ActionCode>
        <BusCode>${TcpCont.BusCode}</BusCode>
        <ServiceCode>${TcpCont.ServiceCode}</ServiceCode>
        <ServiceContractVer>${TcpCont.ServiceContractVer}</ServiceContractVer>
		<ServiceLevel>${TcpCont.ServiceLevel}</ServiceLevel>
		<SrcOrgID>${TcpCont.SrcOrgID}</SrcOrgID>
		<SrcSysID>${TcpCont.SrcSysID}</SrcSysID>
		<SrcSysSign>${TcpCont.SrcSysSign}</SrcSysSign>
		<DstOrgID>${DstOrgID}</DstOrgID>
		<DstSysID>${DstSysID}</DstSysID>
		<ReqTime>${TcpCont.ReqTime}</ReqTime>
		<PackageGroup>${TcpCont.TransactionID}</PackageGroup>
		<TotalPackageNum>1</TotalPackageNum>
		<CurrentPackage>1</CurrentPackage>
	</TcpCont>
	<SvcCont>
	<SOO type="CHECK_LOGIN_INFO_REQ_TYPE">
			<PUB_REQ>
				<SOO_ID>1</SOO_ID>
			</PUB_REQ>
			<TOKEN_INFO>
				<TOKEN>${token}</TOKEN>
			</TOKEN_INFO>
		</SOO>
	</SvcCont>
</ContractRoot>
