<?xml version="1.0" encoding="UTF-8"?>
<ContractRoot>
	<TcpCont>
		<TransactionID>${TcpCont.TransactionID}</TransactionID>
		<ActionCode>${TcpCont.ActionCode}</ActionCode>
        <BusCode>${TcpCont.BusCode}</BusCode>
        <ServiceCode>${TcpCont.ServiceCode}</ServiceCode>
        <ServiceContractVer>${TcpCont.ServiceContractVer}</ServiceContractVer>
		<ServiceLevel>${TcpCont.ServiceLevel}</ServiceLevel>
		<SrcOrgID>${TcpCont.SrcOrgID}</SrcOrgID>
		<SrcSysID>${TcpCont.SrcSysID}</SrcSysID>
		<SrcSysSign>${TcpCont.SrcSysSign}</SrcSysSign>
		<DstOrgID>${TcpCont.DstOrgID}</DstOrgID>
		<DstSysID>${TcpCont.DstSysID}</DstSysID>
		<ReqTime>${TcpCont.ReqTime}</ReqTime>
	</TcpCont>
	<SvcCont>
		<RechargeBalanceReq>
			<Balance_Information>
				<Req_Serial>${TcpCont.TransactionID}</Req_Serial>
				<ChargeGroupId>${chargeGroupId}</ChargeGroupId>
				<#if ownerId??>
				<Charge_Source>0406500000</Charge_Source>
				<#else>
				<Charge_Source>1</Charge_Source>
				</#if>
				<Destination_Id>${phoneNumber}</Destination_Id>
				<Destination_Id_Type>3</Destination_Id_Type>
				<Destination_Attr>2</Destination_Attr>
				<Balance_ItemType_ID>0</Balance_ItemType_ID>
				<UnitType_Id>0</UnitType_Id>
				<FeeAmount>${feeAmount}</FeeAmount>
				<ProlongDays>0</ProlongDays>
				<Channel_Staff_Id>[${channelId}]${staffId}</Channel_Staff_Id>
				<Staff_Code>${staffCode}</Staff_Code>
				<Channel_Name>${channelName}</Channel_Name>
				<RequestAmount>0</RequestAmount>
				<Oper_Date>${operTime}</Oper_Date>
			</Balance_Information>
			<Mvno_Id>${ownerId}</Mvno_Id>
		</RechargeBalanceReq>
	</SvcCont>
</ContractRoot>
