<?xml version="1.0" encoding="UTF-8"?>
<ContractRoot>
	<TcpCont>
		<TransactionID>${TcpCont.TransactionID}</TransactionID>
		<ActionCode>${TcpCont.ActionCode}</ActionCode>
        <BusCode>${TcpCont.BusCode}</BusCode>
        <ServiceCode>${TcpCont.ServiceCode}</ServiceCode>
        <ServiceContractVer>${TcpCont.ServiceContractVer}</ServiceContractVer>
		<ServiceLevel>${TcpCont.ServiceLevel}</ServiceLevel>
		<SrcOrgID>${TcpCont.SrcOrgID}</SrcOrgID>
		<SrcSysID>${TcpCont.SrcSysID}</SrcSysID>
		<SrcSysSign>${TcpCont.SrcSysSign}</SrcSysSign>
		<DstOrgID>${TcpCont.DstOrgID}</DstOrgID>
		<DstSysID>${TcpCont.DstSysID}</DstSysID>
		<ReqTime>${TcpCont.ReqTime}</ReqTime>
	</TcpCont>
	<SvcCont>
		<QueryBalanceReq>
			<BalanceInformation>
				<DestinationId>${phoneNumber}</DestinationId>
				<DestinationIdType>2</DestinationIdType>
				<DestinationAttr>${destinationAttr}</DestinationAttr>
				<QueryFlag>${queryFlag}</QueryFlag>
				<QueryItemType>${queryItemType}</QueryItemType>
			</BalanceInformation>
			<MvnoId>${ownerId}</MvnoId>
		</QueryBalanceReq>
	</SvcCont>
</ContractRoot>