<?xml version="1.0" encoding="UTF-8"?>
<ContractRoot>
	<TcpCont>
		<TransactionID>${TcpCont.TransactionID}</TransactionID>
		<ActionCode>${TcpCont.ActionCode}</ActionCode>
		<BusCode>${TcpCont.BusCode}</BusCode>
        <ServiceCode>${TcpCont.ServiceCode}</ServiceCode>
        <ServiceContractVer>${TcpCont.ServiceContractVer}</ServiceContractVer>
		<ServiceLevel>${TcpCont.ServiceLevel}</ServiceLevel>
		<SrcOrgID>${TcpCont.SrcOrgID}</SrcOrgID>
		<SrcSysID>${TcpCont.SrcSysID}</SrcSysID>
		<SrcSysSign>${TcpCont.SrcSysSign}</SrcSysSign>
		<DstOrgID>${TcpCont.DstOrgID}</DstOrgID>
		<DstSysID>${TcpCont.DstSysID}</DstSysID>
		<ReqTime>${TcpCont.ReqTime}</ReqTime>		
	</TcpCont>
	<SvcCont>
	      <OverDueInPaymentReq>
				    <Operate_Seq>${TcpCont.TransactionID}</Operate_Seq>
				    <Oper_Date>${TcpCont.ReqTime}</Oper_Date>
				    <SpDescription>${spDescription}</SpDescription>
				    <Channel_Staff_Id>[${channelId}]${staffId}</Channel_Staff_Id>
				    <Acct_ID>${acctID}</Acct_ID>
				    <Eff_Date>${effDate}</Eff_Date>
				    <Exp_Date>${expDate}</Exp_Date>
				    <Mvno_Id>${ownerId}</Mvno_Id>
			</OverDueInPaymentReq>
	 </SvcCont>
</ContractRoot>
