<?xml version="1.0" encoding="UTF-8"?>
<ContractRoot>
	<TcpCont>
		<TransactionID>${TcpCont.TransactionID}</TransactionID>
		<ActionCode>${TcpCont.ActionCode}</ActionCode>
        <BusCode>${TcpCont.BusCode}</BusCode>
        <ServiceCode>${TcpCont.ServiceCode}</ServiceCode>
        <ServiceContractVer>${TcpCont.ServiceContractVer}</ServiceContractVer>
		<ServiceLevel>${TcpCont.ServiceLevel}</ServiceLevel>
		<SrcOrgID>${TcpCont.SrcOrgID}</SrcOrgID>
		<SrcSysID>${TcpCont.SrcSysID}</SrcSysID>
		<SrcSysSign>${TcpCont.SrcSysSign}</SrcSysSign>
		<DstOrgID>${TcpCont.DstOrgID}</DstOrgID>
		<DstSysID>${TcpCont.DstSysID}</DstSysID>
		<ReqTime>${TcpCont.ReqTime}</ReqTime>
	</TcpCont>
	<SvcCont>
		<BalDrawBalanceReq>
			<Balance_Information>
				<Destination_Id>${phoneNumber}</Destination_Id>
				<Destination_Id_Type>2</Destination_Id_Type>
				<Destination_Attr>${destinationAttr}</Destination_Attr>
				<AreaCode>${areaCode}</AreaCode>
				<Query_Flag>${queryFlag}</Query_Flag>
				<Balance_Amount>${feeAmount}</Balance_Amount>
				<Channel_Staff_Id>[${channelId}]${staffId}</Channel_Staff_Id>
				<Oper_Date>${operTime}</Oper_Date>
			</Balance_Information>
			<Mvno_Id>${ownerId}</Mvno_Id>
		</BalDrawBalanceReq>
	</SvcCont>
</ContractRoot>
