<?xml version="1.0" encoding="UTF-8"?>
<ContractRoot>
	<TcpCont>
		<TransactionID>${TcpCont.TransactionID}</TransactionID>
		<ActionCode>${TcpCont.ActionCode}</ActionCode>
		<BusCode>BUS61004</BusCode>
		<ServiceCode>SVC83015</ServiceCode>
		<ServiceContractVer>SVC8301520131028</ServiceContractVer>
		<ServiceLevel>${TcpCont.ServiceLevel}</ServiceLevel>
		<SrcOrgID>${TcpCont.SrcOrgID}</SrcOrgID>
		<SrcSysID>${TcpCont.SrcSysID}</SrcSysID>
		<SrcSysSign>123</SrcSysSign>
		<DstOrgID>100000</DstOrgID>
		<DstSysID>1000000203</DstSysID>
		<ReqTime>${TcpCont.ReqTime}</ReqTime>
	</TcpCont>
	<SvcCont>
		<CustomizeBillPrintBillReq>
			<Bill_Information>
				<Acc_Nbr>${phoneNumber}</Acc_Nbr>
				<Billing_Cycle>${billingCycle}</Billing_Cycle>
				<Channel>3</Channel>
				<Query_Flag>${queryFlag}</Query_Flag>
				<Mvno_Id>${ownerId}</Mvno_Id>
			</Bill_Information>	
		</CustomizeBillPrintBillReq>
	</SvcCont>
</ContractRoot>
