<?xml version="1.0" encoding="UTF-8"?>
<ContractRoot>
	<TcpCont>
		<TransactionID>${TcpCont.TransactionID}</TransactionID>
		<ActionCode>${TcpCont.ActionCode}</ActionCode>
		<!--具体的业务编码-->
		<BusCode>BUS61004</BusCode>
		<!--具体的服务编码-->
		<ServiceCode>SVC83003</ServiceCode>
		<!--协议当前使用的版本号-->
		<ServiceContractVer>SVC8300320131028</ServiceContractVer>
		<ServiceLevel>${TcpCont.ServiceLevel}</ServiceLevel>
		<SrcOrgID>${TcpCont.SrcOrgID}</SrcOrgID>
		<SrcSysID>${TcpCont.SrcSysID}</SrcSysID>
		<SrcSysSign>123</SrcSysSign>
		<DstOrgID>100000</DstOrgID>
		<DstSysID>1000000203</DstSysID>
		<ReqTime>${TcpCont.ReqTime}</ReqTime>
	</TcpCont>
	<SvcCont>
		<SMSUDRQueryReq>
			<Destination_Id>${destinationId}</Destination_Id>
			<BillingCycle>${billingCycle}</BillingCycle>
			<Query_Flag>${queryFlag}</Query_Flag>
			<Query_Event_Type>${eventType}</Query_Event_Type>
			<Pages>${curPage}</Pages>
			<Count>${pageSize}</Count>
			<MvnoId>${ownerId}</MvnoId>
		</SMSUDRQueryReq>
	</SvcCont>
</ContractRoot>
