<?xml version="1.0" encoding="UTF-8"?>
<ContractRoot>
	<TcpCont>
		<TransactionID>${TcpCont.TransactionID}</TransactionID>
		<ActionCode>${TcpCont.ActionCode}</ActionCode>
        <BusCode>${TcpCont.BusCode}</BusCode>
        <ServiceCode>${TcpCont.ServiceCode}</ServiceCode>
        <ServiceContractVer>${TcpCont.ServiceContractVer}</ServiceContractVer>
		<ServiceLevel>${TcpCont.ServiceLevel}</ServiceLevel>
		<SrcOrgID>${TcpCont.SrcOrgID}</SrcOrgID>
		<SrcSysID>${TcpCont.SrcSysID}</SrcSysID>
		<SrcSysSign>${TcpCont.SrcSysSign}</SrcSysSign>
		<DstOrgID>${TcpCont.DstOrgID}</DstOrgID>
		<DstSysID>${TcpCont.DstSysID}</DstSysID>
		<ReqTime>${TcpCont.ReqTime}</ReqTime>
	</TcpCont>
	<SvcCont>
		<RechargeRefundReq>
			<VC_Information>
				<Req_Serial>${TcpCont.TransactionID}</Req_Serial>
				<Res_Serial>${reqSerial}</Res_Serial>
				<Destination_Account>${phoneNumber}</Destination_Account>
				<Destination_Attr>${destinationAttr}</Destination_Attr>
				<Channel_Staff_Id>[${channelId}]${staffId}</Channel_Staff_Id>
				<Oper_Date>${operTime}</Oper_Date>
			</VC_Information>
			<Mvno_Id>${ownerId}</Mvno_Id>
		</RechargeRefundReq>
	</SvcCont>
</ContractRoot>
