<?xml version="1.0" encoding="UTF-8"?>
<ContractRoot>
	<TcpCont>
		<TransactionID>${TcpCont.TransactionID}</TransactionID>
		<ActionCode>${TcpCont.ActionCode}</ActionCode>
        <BusCode>${TcpCont.BusCode}</BusCode>
        <ServiceCode>${TcpCont.ServiceCode}</ServiceCode>
        <ServiceContractVer>${TcpCont.ServiceContractVer}</ServiceContractVer>
		<ServiceLevel>${TcpCont.ServiceLevel}</ServiceLevel>
		<SrcOrgID>${TcpCont.SrcOrgID}</SrcOrgID>
		<SrcSysID>${TcpCont.SrcSysID}</SrcSysID>
		<SrcSysSign>${TcpCont.SrcSysSign}</SrcSysSign>
		<DstOrgID>${TcpCont.DstOrgID}</DstOrgID>
		<DstSysID>${TcpCont.DstSysID}</DstSysID>
		<ReqTime>${TcpCont.ReqTime}</ReqTime>
	</TcpCont>
	<SvcCont>
		<ReversePaymentReq>
			<Reverse>
				<Serial_Type>${serialType}</Serial_Type>
				<Serial_Nbr>${serialNbr}</Serial_Nbr>
				<Latn_Id>${areaCode}</Latn_Id>
				<Acc_Nbr>${phoneNumber}</Acc_Nbr>
				<Channel_Staff_Id>[${channelId}]${staffId}</Channel_Staff_Id>
				<Oper_Date>${operTime}</Oper_Date>
			</Reverse>
			<Mvno_Id>${ownerId}</Mvno_Id>
		</ReversePaymentReq>
	</SvcCont>
</ContractRoot>
