<?xml version="1.0" encoding="UTF-8"?>
<ContractRoot>
	<TcpCont>
		<Response>
			<RspCode>0000</RspCode>
			<RspDesc>成功</RspDesc>		
		</Response>
	</TcpCont>
	<SvcCont>
		<BillQueryByAcctIDRsp>
				<Service_Result_Code></Service_Result_Code>
				<Para_Field_Result></Para_Field_Result>
				<Bill_Query_Information>
					<Acct_ID>1111</Acct_ID>
					<Acct_Name>账户名</Acct_Name>
					<Acc_Nbr>18900000000</Acc_Nbr>
					<Fee_Billing_Cycle>
						<Billing_Cycle_ID>19991111</Billing_Cycle_ID>
						<Acct_Item_Group>
							<Acct_Item_Group_Id>222</Acct_Item_Group_Id>
							<Acct_Item_Type>
								<Acct_Item_Type_Name>费用1</Acct_Item_Type_Name>
								<Acct_Item_Charge>100</Acct_Item_Charge>
							</Acct_Item_Type>
							<Acct_Item_Type>
								<Acct_Item_Type_Name>费用2</Acct_Item_Type_Name>
								<Acct_Item_Charge>200</Acct_Item_Charge>
							</Acct_Item_Type>							
						</Acct_Item_Group>
						<Acct_Item_Group>
							<Acct_Item_Group_Id>1111111</Acct_Item_Group_Id>
							<Acct_Item_Type>
								<Acct_Item_Type_Name>费用1</Acct_Item_Type_Name>
								<Acct_Item_Charge>100</Acct_Item_Charge>
							</Acct_Item_Type>
							<Acct_Item_Type>
								<Acct_Item_Type_Name>费用2</Acct_Item_Type_Name>
								<Acct_Item_Charge>200</Acct_Item_Charge>
							</Acct_Item_Type>							
						</Acct_Item_Group>						
					</Fee_Billing_Cycle>
					<Fee_Billing_Cycle>
						<Billing_Cycle_ID>20001111</Billing_Cycle_ID>
						<Acct_Item_Group>
							<Acct_Item_Group_Id>222</Acct_Item_Group_Id>
							<Acct_Item_Type>
								<Acct_Item_Type_Name>费用1</Acct_Item_Type_Name>
								<Acct_Item_Charge>100</Acct_Item_Charge>
							</Acct_Item_Type>
							<Acct_Item_Type>
								<Acct_Item_Type_Name>费用2</Acct_Item_Type_Name>
								<Acct_Item_Charge>200</Acct_Item_Charge>
							</Acct_Item_Type>							
						</Acct_Item_Group>
						<Acct_Item_Group>
							<Acct_Item_Group_Id>1111111</Acct_Item_Group_Id>
							<Acct_Item_Type>
								<Acct_Item_Type_Name>费用1</Acct_Item_Type_Name>
								<Acct_Item_Charge>100</Acct_Item_Charge>
							</Acct_Item_Type>
							<Acct_Item_Type>
								<Acct_Item_Type_Name>费用2</Acct_Item_Type_Name>
								<Acct_Item_Charge>200</Acct_Item_Charge>
							</Acct_Item_Type>							
						</Acct_Item_Group>						
					</Fee_Billing_Cycle>					
					<Due>11220</Due>
					<Derate_Due>1120</Derate_Due>
					<Valid_Balance>1122</Valid_Balance>
					<Should_Charge>1122</Should_Charge>
					<Previous_Change>112</Previous_Change>
					<Current_Change>122</Current_Change>
				</Bill_Query_Information>
		</BillQueryByAcctIDRsp>

	</SvcCont>
</ContractRoot>
