<?xml version="1.0" encoding="UTF-8"?>
<ContractRoot>
	<TcpCont>
		<Response>
			<RspCode>0000</RspCode>
			<RspDesc>成功</RspDesc>		
		</Response>
	</TcpCont>
	<SvcCont>
		<Service_Information>
			<Service_Result_Code>0</Service_Result_Code>
			<Payment_Record_info>
				<Payment_Amount>12400</Payment_Amount>
				<Payment_Method>14</Payment_Method>
				<Paid_Time>2013-11-11</Paid_Time>
			</Payment_Record_info>
			<Payment_Record_info>
				<Payment_Amount>10026</Payment_Amount>
				<Payment_Method>14</Payment_Method>
				<Paid_Time>2013-11-11</Paid_Time>
			</Payment_Record_info>
			<Payment_Record_info>
				<Payment_Amount>10000</Payment_Amount>
				<Payment_Method>15</Payment_Method>
				<Paid_Time>2013-11-11</Paid_Time>
			</Payment_Record_info>
			<Payment_Record_info>
				<Payment_Amount>10000</Payment_Amount>
				<Payment_Method>15</Payment_Method>
				<Paid_Time>2013-11-11</Paid_Time>
			</Payment_Record_info>
		</Service_Information>
	</SvcCont>
</ContractRoot>
