<?xml version="1.0" encoding="UTF-8"?>
<ContractRoot>
	<TcpCont>
		<Response>
			<RspCode>0000</RspCode>
			<RspDesc>成功</RspDesc>		
		</Response>
	</TcpCont>
	<SvcCont>
		<Service_Information>
			<Service_Result_Code>0</Service_Result_Code>
			<Bill_Information>
				<TotalBalanceAvailable>4000</TotalBalanceAvailable>
				<ProductOFInfo>
					<ProdOffName>乐享4G-128套餐</ProdOffName>
					<StartDate>20131125</StartDate>
					<EndDate>20131125</EndDate>
					<AccuInfo>
						<OwnerType>1</OwnerType>
						<OwnerID>1</OwnerID>
						<AccuRscID>1</AccuRscID>
						<AccuRscname>累积量名称</AccuRscname>
						<StartTime>20131125</StartTime>
						<EndTime>20131125</EndTime>
						<AccuAmount>300</AccuAmount>
						<BalanceAmount>200</BalanceAmount>
						<UnitTypeId>0</UnitTypeId>
					</AccuInfo>
					<AccuInfo>
						<OwnerType>1</OwnerType>
						<OwnerID>1</OwnerID>
						<AccuRscID>1</AccuRscID>
						<AccuRscname>累积量名称222</AccuRscname>
						<StartTime>20131125</StartTime>
						<EndTime>20131125</EndTime>
						<AccuAmount>300</AccuAmount>
						<BalanceAmount>200</BalanceAmount>
						<UnitTypeId>0</UnitTypeId>
					</AccuInfo>
					<AccuInfo>
						<OwnerType>1</OwnerType>
						<OwnerID>1</OwnerID>
						<AccuRscID>1</AccuRscID>
						<AccuRscname>累积量名111称</AccuRscname>
						<StartTime>20131125</StartTime>
						<EndTime>20131125</EndTime>
						<AccuAmount>300</AccuAmount>
						<BalanceAmount>200</BalanceAmount>
						<UnitTypeId>1</UnitTypeId>
					</AccuInfo>
				</ProductOFInfo>
				<ProductOFInfo>
					<ProdOffName>乐享4G-69套餐</ProdOffName>
					<StartDate>20131125</StartDate>
					<EndDate>20131125</EndDate>
					<AccuInfo>
						<OwnerType>1</OwnerType>
						<OwnerID>1</OwnerID>
						<AccuRscID>1</AccuRscID>
						<AccuRscname>累积量11名称</AccuRscname>
						<StartTime>20131125</StartTime>
						<EndTime>20131125</EndTime>
						<AccuAmount>300</AccuAmount>
						<BalanceAmount>200</BalanceAmount>
						<UnitTypeId>0</UnitTypeId>
					</AccuInfo>
					<AccuInfo>
						<OwnerType>1</OwnerType>
						<OwnerID>1</OwnerID>
						<AccuRscID>1</AccuRscID>
						<AccuRscname>累积量名称</AccuRscname>
						<StartTime>20131125</StartTime>
						<EndTime>20131125</EndTime>
						<AccuAmount>300</AccuAmount>
						<BalanceAmount>200</BalanceAmount>
						<UnitTypeId>1</UnitTypeId>
					</AccuInfo>
										<AccuInfo>
						<OwnerType>1</OwnerType>
						<OwnerID>1</OwnerID>
						<AccuRscID>1</AccuRscID>
						<AccuRscname>累积量名称</AccuRscname>
						<StartTime>20131125</StartTime>
						<EndTime>20131125</EndTime>
						<AccuAmount>300</AccuAmount>
						<BalanceAmount>200</BalanceAmount>
						<UnitTypeId>2</UnitTypeId>
					</AccuInfo>
										<AccuInfo>
						<OwnerType>1</OwnerType>
						<OwnerID>1</OwnerID>
						<AccuRscID>1</AccuRscID>
						<AccuRscname>累积量222名称</AccuRscname>
						<StartTime>20131125</StartTime>
						<EndTime>20131125</EndTime>
						<AccuAmount>300</AccuAmount>
						<BalanceAmount>200</BalanceAmount>
						<UnitTypeId>1</UnitTypeId>
					</AccuInfo>
				</ProductOFInfo>				
			</Bill_Information>
		</Service_Information>
	</SvcCont>
</ContractRoot>
