<?xml version="1.0" encoding="UTF-8"?>
<ContractRoot>
	<TcpCont>
		<Response>
			<RspCode>0000</RspCode>
			<RspDesc>成功</RspDesc>		
		</Response>
	</TcpCont>
	<SvcCont>
		<Service_Information>
			<Service_Result_Code>0</Service_Result_Code>
			<Bill_Information>
				<Sum_Charge>0</Sum_Charge>
				<Acct_Name>陈玉珠</Acct_Name>
				<Item_Information>
					<Show_level>1</Show_level>
					<Class_Id>18881</Class_Id>
					<Parent_Class_Id>0</Parent_Class_Id>
					<Charge_type_Name>移动手机上网业务信息费1级</Charge_type_Name>
					<Charge>-500</Charge>
				</Item_Information>
								
				<Item_Information>
					<Show_level>2</Show_level>
					<Class_Id>111</Class_Id>
					<Parent_Class_Id>18881</Parent_Class_Id>
					<Charge_type_Name>移动手机上网业务信息费_音乐下载2级</Charge_type_Name>
					<Charge>-500</Charge>
				</Item_Information>
				
				<Item_Information>
					<Show_level>3</Show_level>
					<Class_Id>112</Class_Id>
					<Parent_Class_Id>111</Parent_Class_Id>
					<Charge_type_Name>移动手机上网业务信息费_音乐下载3级</Charge_type_Name>
					<Charge>-500</Charge>
				</Item_Information>
				
				<Item_Information>
					<Show_level>4</Show_level>
					<Class_Id>113</Class_Id>
					<Parent_Class_Id>112</Parent_Class_Id>
					<Charge_type_Name>移动手机上网业务信息费_音乐下载4级</Charge_type_Name>
					<Charge>-500</Charge>
				</Item_Information>
				
											
				<Item_Information>
					<Show_level>1</Show_level>
					<Class_Id>18882</Class_Id>
					<Parent_Class_Id>0</Parent_Class_Id>
					<Charge_type_Name>移动手机上网业务信息费_音乐下载</Charge_type_Name>
					<Charge>500</Charge>
				</Item_Information>
				<Item_Information>
					<Show_level>1</Show_level>
					<Class_Id>17914</Class_Id>
					<Parent_Class_Id>0</Parent_Class_Id>
					<Charge_type_Name>VPN网内包月月租</Charge_type_Name>
					<Charge>-30</Charge>
				</Item_Information>
				<Item_Information>
					<Show_level>1</Show_level>
					<Class_Id>17914</Class_Id>
					<Parent_Class_Id>0</Parent_Class_Id>
					<Charge_type_Name>VPN网内包月月租</Charge_type_Name>
					<Charge>-3</Charge>
				</Item_Information>
				<Item_Information>
					<Show_level>1</Show_level>
					<Class_Id>17914</Class_Id>
					<Parent_Class_Id>0</Parent_Class_Id>
					<Charge_type_Name>VPN网内包月月租</Charge_type_Name>
					<Charge>33</Charge>
				</Item_Information>
				<Item_Information>
					<Show_level>1</Show_level>
					<Class_Id>17813</Class_Id>
					<Parent_Class_Id>0</Parent_Class_Id>
					<Charge_type_Name>移动业务无线宽带业务互联星空/无线上网包月费</Charge_type_Name>
					<Charge>-1000</Charge>
				</Item_Information>
				<Item_Information>
					<Show_level>1</Show_level>
					<Class_Id>17813</Class_Id>
					<Parent_Class_Id>0</Parent_Class_Id>
					<Charge_type_Name>移动业务无线宽带业务互联星空/无线上网包月费</Charge_type_Name>
					<Charge>1000</Charge>
				</Item_Information>
				<Item_Information>
					<Show_level>1</Show_level>
					<Class_Id>16964</Class_Id>
					<Parent_Class_Id>0</Parent_Class_Id>
					<Charge_type_Name>移动业务补齐最低消费</Charge_type_Name>
					<Charge>-527</Charge>
				</Item_Information>
				<Item_Information>
					<Show_level>1</Show_level>
					<Class_Id>16964</Class_Id>
					<Parent_Class_Id>0</Parent_Class_Id>
					<Charge_type_Name>移动业务补齐最低消费</Charge_type_Name>
					<Charge>527</Charge>
				</Item_Information>
				<Item_Information>
					<Show_level>1</Show_level>
					<Class_Id>16896</Class_Id>
					<Parent_Class_Id>0</Parent_Class_Id>
					<Charge_type_Name>移动业务移动国内点对点短信通信费</Charge_type_Name>
					<Charge>-36</Charge>
				</Item_Information>
				<Item_Information>
					<Show_level>1</Show_level>
					<Class_Id>16896</Class_Id>
					<Parent_Class_Id>0</Parent_Class_Id>
					<Charge_type_Name>移动业务移动国内点对点短信通信费</Charge_type_Name>
					<Charge>-4</Charge>
				</Item_Information>
				<Item_Information>
					<Show_level>1</Show_level>
					<Class_Id>16896</Class_Id>
					<Parent_Class_Id>0</Parent_Class_Id>
					<Charge_type_Name>移动业务移动国内点对点短信通信费</Charge_type_Name>
					<Charge>40</Charge>
				</Item_Information>
				<Item_Information>
					<Show_level>1</Show_level>
					<Class_Id>16840</Class_Id>
					<Parent_Class_Id>0</Parent_Class_Id>
					<Charge_type_Name>移动业务省内漫游移动费</Charge_type_Name>
					<Charge>-1800</Charge>
				</Item_Information>
				<Item_Information>
					<Show_level>1</Show_level>
					<Class_Id>16840</Class_Id>
					<Parent_Class_Id>0</Parent_Class_Id>
					<Charge_type_Name>移动业务省内漫游移动费</Charge_type_Name>
					<Charge>-5880</Charge>
				</Item_Information>
				<Item_Information>
					<Show_level>1</Show_level>
					<Class_Id>16840</Class_Id>
					<Parent_Class_Id>0</Parent_Class_Id>
					<Charge_type_Name>移动业务省内漫游移动费</Charge_type_Name>
					<Charge>7680</Charge>
				</Item_Information>
				<Item_Information>
					<Show_level>1</Show_level>
					<Class_Id>16712</Class_Id>
					<Parent_Class_Id>0</Parent_Class_Id>
					<Charge_type_Name>移动业务手机上网费</Charge_type_Name>
					<Charge>-3632</Charge>
				</Item_Information>
				<Item_Information>
					<Show_level>1</Show_level>
					<Class_Id>16712</Class_Id>
					<Parent_Class_Id>0</Parent_Class_Id>
					<Charge_type_Name>移动业务手机上网费</Charge_type_Name>
					<Charge>-871</Charge>
				</Item_Information>
				<Item_Information>
					<Show_level>1</Show_level>
					<Class_Id>16712</Class_Id>
					<Parent_Class_Id>0</Parent_Class_Id>
					<Charge_type_Name>移动业务手机上网费</Charge_type_Name>
					<Charge>4503</Charge>
				</Item_Information>
				<Item_Information>
					<Show_level>1</Show_level>
					<Class_Id>16514</Class_Id>
					<Parent_Class_Id>0</Parent_Class_Id>
					<Charge_type_Name>移动业务_手机支付_公交翼卡通功能费</Charge_type_Name>
					<Charge>-91</Charge>
				</Item_Information>
				<Item_Information>
					<Show_level>1</Show_level>
					<Class_Id>16514</Class_Id>
					<Parent_Class_Id>0</Parent_Class_Id>
					<Charge_type_Name>移动业务_手机支付_公交翼卡通功能费</Charge_type_Name>
					<Charge>-9</Charge>
				</Item_Information>
				<Item_Information>
					<Show_level>1</Show_level>
					<Class_Id>16514</Class_Id>
					<Parent_Class_Id>0</Parent_Class_Id>
					<Charge_type_Name>移动业务_手机支付_公交翼卡通功能费</Charge_type_Name>
					<Charge>100</Charge>
				</Item_Information>
				<Item_Information>
					<Show_level>1</Show_level>
					<Class_Id>16150</Class_Id>
					<Parent_Class_Id>0</Parent_Class_Id>
					<Charge_type_Name>套餐使用费</Charge_type_Name>
					<Charge>-2694</Charge>
				</Item_Information>
				<Item_Information>
					<Show_level>1</Show_level>
					<Class_Id>16150</Class_Id>
					<Parent_Class_Id>0</Parent_Class_Id>
					<Charge_type_Name>套餐使用费</Charge_type_Name>
					<Charge>2966</Charge>
				</Item_Information>
				<Item_Information>
					<Show_level>1</Show_level>
					<Class_Id>16150</Class_Id>
					<Parent_Class_Id>0</Parent_Class_Id>
					<Charge_type_Name>套餐使用费</Charge_type_Name>
					<Charge>-272</Charge>
				</Item_Information>
				<Item_Information>
					<Show_level>1</Show_level>
					<Class_Id>16014</Class_Id>
					<Parent_Class_Id>0</Parent_Class_Id>
					<Charge_type_Name>移动电话基本月租(非套餐使用)</Charge_type_Name>
					<Charge>-1667</Charge>
				</Item_Information>
				<Item_Information>
					<Show_level>1</Show_level>
					<Class_Id>16014</Class_Id>
					<Parent_Class_Id>0</Parent_Class_Id>
					<Charge_type_Name>移动电话基本月租(非套餐使用)</Charge_type_Name>
					<Charge>1667</Charge>
				</Item_Information>
				<Item_Information>
					<Show_level>1</Show_level>
					<Class_Id>16001</Class_Id>
					<Parent_Class_Id>0</Parent_Class_Id>
					<Charge_type_Name>移动来电显示月租费</Charge_type_Name>
					<Charge>-200</Charge>
				</Item_Information>
				<Item_Information>
					<Show_level>1</Show_level>
					<Class_Id>16001</Class_Id>
					<Parent_Class_Id>0</Parent_Class_Id>
					<Charge_type_Name>移动来电显示月租费</Charge_type_Name>
					<Charge>200</Charge>
				</Item_Information>
			</Bill_Information>
		</Service_Information>
	</SvcCont>
</ContractRoot>
