<?xml version="1.0" encoding="UTF-8"?>
<ContractRoot>
	<TcpCont>
		<Response>
			<RspCode>0000</RspCode>
			<RspDesc>成功</RspDesc>		
		</Response>
	</TcpCont>
	<SvcCont>
		<Service_Information>
			<Service_Result_Code>0</Service_Result_Code>
			<Balance_Information>
				<Balance_ItemType_ID>2</Balance_ItemType_ID>
				<UnitType_Id>0</UnitType_Id>
				<Balance_Amount>14000</Balance_Amount>
				<EffectiveTime>20100101</EffectiveTime>
				<ExpirationTime>20301231</ExpirationTime>
			</Balance_Information>
		</Service_Information>
	</SvcCont>
</ContractRoot>
