<?xml version="1.0" encoding="UTF-8"?>
<ContractRoot>
	<TcpCont>
		<Response>
			<RspCode>0000</RspCode>
			<RspDesc>成功</RspDesc>		
		</Response>
	</TcpCont>
	<SvcCont>
		<Service_Information>
		    <Service_Result_Code></Service_Result_Code>
		    <Para_Field_Result></Para_Field_Result>
			<Write_Off_Information>
				<Bill_Serial_Nbr>1111</Bill_Serial_Nbr>
				<Payment_Serial_Nbr>22222</Payment_Serial_Nbr>
				<Billing_Cycle_Group>
					<Billing_Cycle_ID>20110101</Billing_Cycle_ID>
				</Billing_Cycle_Group>
				<Billing_Cycle_Group>
					<Billing_Cycle_ID>20110201</Billing_Cycle_ID>
				</Billing_Cycle_Group>
				<Sum_Charge>2333</Sum_Charge>
				<Previous_Change>2333</Previous_Change>
				<Current_Change>2333</Current_Change>
			</Write_Off_Information>
			<Write_Off_Information>
				<Bill_Serial_Nbr>1111</Bill_Serial_Nbr>
				<Payment_Serial_Nbr>22222</Payment_Serial_Nbr>
				<Billing_Cycle_Group>
					<Billing_Cycle_ID>20110101</Billing_Cycle_ID>
				</Billing_Cycle_Group>
				<Billing_Cycle_Group>
					<Billing_Cycle_ID>20110201</Billing_Cycle_ID>
				</Billing_Cycle_Group>				
				<Sum_Charge>2333</Sum_Charge>
				<Previous_Change>2333</Previous_Change>
				<Current_Change>2333</Current_Change>
			</Write_Off_Information>
			<Write_Off_Information>
				<Bill_Serial_Nbr>1111</Bill_Serial_Nbr>
				<Payment_Serial_Nbr>22222</Payment_Serial_Nbr>
				<Billing_Cycle_Group>
					<Billing_Cycle_ID>20110201</Billing_Cycle_ID>
				</Billing_Cycle_Group>
				<Sum_Charge>111</Sum_Charge>
				<Previous_Change>111</Previous_Change>
				<Current_Change>222</Current_Change>
			</Write_Off_Information>						
		</Service_Information>
	</SvcCont>
</ContractRoot>
