<?xml version="1.0" encoding="UTF-8"?>
<ContractRoot>
	<TcpCont>
		<TransactionID>${TcpCont.TransactionID}</TransactionID>
		<ActionCode>${TcpCont.ActionCode}</ActionCode>
		<BusCode>${TcpCont.BusCode}</BusCode>
        <ServiceCode>${TcpCont.ServiceCode}</ServiceCode>
        <ServiceContractVer>${TcpCont.ServiceContractVer}</ServiceContractVer>
		<ServiceLevel>${TcpCont.ServiceLevel}</ServiceLevel>
		<SrcOrgID>${TcpCont.SrcOrgID}</SrcOrgID>
		<SrcSysID>${TcpCont.SrcSysID}</SrcSysID>
		<SrcSysSign>${TcpCont.SrcSysSign}</SrcSysSign>
		<DstOrgID>${TcpCont.DstOrgID}</DstOrgID>
		<DstSysID>${TcpCont.DstSysID}</DstSysID>
		<ReqTime>${TcpCont.ReqTime}</ReqTime>		
	</TcpCont>
	<SvcCont>
		<WriteOffPaymentReq>
			<Write_Off>
				<BillQuery_Type>2</BillQuery_Type>
				<Destination_Account>${phoneNumber}</Destination_Account>
				<Query_Flag>0</Query_Flag>
				<Payment_Amount>${paymentAmount}</Payment_Amount>
				<Payment_Method>${paymentMethod}</Payment_Method>
				<Billing_Cycle_ID>${billingCycleId}</Billing_Cycle_ID>
				<Invoice_Offer>${invoiceOffer}</Invoice_Offer>
				<Channel_Staff_Id>[${channelId}]${staffId}</Channel_Staff_Id>
				<Oper_Date>${operTime}</Oper_Date>
			</Write_Off>
			<Mvno_Id>${ownerId}</Mvno_Id>
		</WriteOffPaymentReq>
	</SvcCont>
</ContractRoot>
