<orderList>
	<orderListInfo>
		<extCustOrderId>${orderNo}</extCustOrderId>
		<areaName></areaName>
		<areaId></areaId>
	</orderListInfo>
	<!--客户订单信息--start-->
	<custOrderList>
		<partyId>223001714838</partyId>
		<partyName>${item.cust.name}</partyName>
		<addressStr>${item.cust.address}</addressStr>
		<identityType>${item.cust.idType}</identityType>
		<identityCardNo>${item.cust.idNo}</identityCardNo>
		<linkName>${item.cust.name}</linkName>
		<linkNumber>${item.phonenumber.number}</linkNumber>
		<partyChangeInfo>
			<partyBaseInfo>
				<simpleSpell></simpleSpell>
				<areaName></areaName>
				<partyTypeName></partyTypeName>
				<defultIdentify></defultIdentify>
				<industryClassName></industryClassName>
				<professionName></professionName>
				<busPwd></busPwd>
				<quePwd></quePwd>
				<addressStr></addressStr>
				<mailAddressStr></mailAddressStr>
			</partyBaseInfo>
			<partyIdentifyInfo>
				<identifyTypeName></identifyTypeName>
				<identityNum></identityNum>
			</partyIdentifyInfo>
			<partyProfileInfo>
				<profileType></profileType>
				<profileValue></profileValue>
			</partyProfileInfo>
		</partyChangeInfo>
		<orderEvent>
			<busiOrderInfos>
				<busiOrderInfo>
					<boActionName></boActionName>
					<objName>新装</objName>
				</busiOrderInfo>
			</busiOrderInfos>
			<packageMsg></packageMsg>
			<partyInfos>
				<partyInfo>
					<action></action>
					<partyName></partyName>
					<identityType></identityType>
					<identityNum></identityNum>
				</partyInfo>
			</partyInfos>
			<prodInfos>
				<prodInfo>
					<roleAction></roleAction>
					<roleName></roleName>
					<prodSpecName></prodSpecName>
					<prodAction></prodAction>
					<boProdAn>
						<accessNumber>${item.phonenumber.number}</accessNumber>
						<action></action>
					</boProdAn>
					<boProd2An>
						<action></action>
						<typeName></typeName>
						<accessNumber></accessNumber>
					</boProd2An>
					<addressDesc></addressDesc>
					<boProdAddress>
						<action></action>
						<addrDetail></addrDetail>
					</boProdAddress>
					<stopStartTime></stopStartTime>
					<prodStatusCd></prodStatusCd>
					<stopEndTime></stopEndTime>
					<prodItem>
						<itemSpecName></itemSpecName>
						<content>
							<action></action>
							<value></value>
						</content>
					</prodItem>
					<prodCompItem>
						<itemSpecName></itemSpecName>
						<content>
							<action></action>
							<value></value>
						</content>
					</prodCompItem>
					<servInfo>
						<action></action>
						<servSpecName></servSpecName>
						<servItem>
							<itemSpecName></itemSpecName>
							<content>
								<action></action>
								<value></value>
							</content>
						</servItem>
					</servInfo>
				</prodInfo>
			</prodInfos>
			<!--套餐信息--start-->
			<offerInfos>
				<#list item.offer as it>
				<offerInfo>
					<action></action>
					<offerSpecName>${it.name}</offerSpecName>
					<ooParam>
						<itemSpecName></itemSpecName>
						<content>
							<action>${it.action}</action>
							<value></value>
						</content>
					</ooParam>
					<startDt></startDt>
					<endDt></endDt>
					<effTime></effTime>
					<timeUnit></timeUnit>
					<offerSpecDesc></offerSpecDesc>
				</offerInfo>
				</#list>
			</offerInfos>
			<!--套餐信息--end-->
			<orderAttrs>
				<orderAttr>
					<name></name>
					<value></value>
				</orderAttr>
			</orderAttrs>
			<boProdTds>
				<boProdTd>
					<action></action>
					<deviceModelName></deviceModelName>
					<band></band>
					<pattern></pattern> 
					<color></color>
					<terminalCode></terminalCode>
					<iccid></iccid>
				</boProdTd>
			</boProdTds>
			<!--终端信息--start-->
			<boCoupons>
				<boCoupon>
					<action>${item.mhk.action}</action>
					<couponName>${item.mhk.mktResName}</couponName>
					<amount>${item.mhk.price}</amount>
					<insNbr>${item.mhk.mktResCd}</insNbr>
				</boCoupon>
				<boCoupon>
					<action></action>
					<couponName></couponName>
					<amount></amount>
					<insNbr>${item.uim.uim}</insNbr>
				</boCoupon>
			</boCoupons>
			<!--终端信息--end-->
			<boAccountInfos>
				<boAccountInfo>
					<acctName></acctName>
					<paymentAcct>
						<payAction></payAction>
						<payAcctType></payAcctType>
						<bankName></bankName>
						<bankAcct></bankAcct>
						<payMan></payMan>
					</paymentAcct>
				</boAccountInfo>
			</boAccountInfos>
			<linkMsg>
				<actionDetail></actionDetail>
				<helpMan></helpMan>
				<assureMan></assureMan>
				<userMan></userMan>
				<passMan></passMan>
				<linkMan></linkMan>
				<linkNbr></linkNbr>
			</linkMsg>
			<boActionRemarks>
				<boActionRemark>
					<remark></remark>
				</boActionRemark>
			</boActionRemarks>
		</orderEvent>
	</custOrderList>
<!--客户订单信息--start-->
</orderList>